// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Article struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	Brief      string   `json:"brief"`
	Content    string   `json:"content"`
	CategoryID string   `json:"categoryID"`
	Tags       []string `json:"tags"`
}

type ArticleInput struct {
	Name       string   `json:"name"`
	CategoryID string   `json:"categoryID"`
	Brief      string   `json:"brief"`
	Content    string   `json:"content"`
	Tags       []string `json:"tags"`
}

type ArticleResponse struct {
	Message  string     `json:"message"`
	Status   int        `json:"status"`
	Data     *Article   `json:"data"`
	DataList []*Article `json:"dataList"`
}

type Category struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	ParentID string `json:"parentID"`
}

type CategoryInput struct {
	Name     string `json:"name"`
	ParentID string `json:"parentID"`
}

type CategoryResponse struct {
	Message  string      `json:"message"`
	Status   int         `json:"status"`
	Data     *Category   `json:"data"`
	DataList []*Category `json:"dataList"`
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type TagInput struct {
	Name string `json:"name"`
}

type TagResponse struct {
	Message  string `json:"message"`
	Status   int    `json:"status"`
	Data     *Tag   `json:"data"`
	DataList []*Tag `json:"dataList"`
}

type User struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	EmailAddress string `json:"emailAddress"`
	Password     string `json:"password"`
}

type UserInput struct {
	Username     string `json:"username"`
	EmailAddress string `json:"emailAddress"`
	Password     string `json:"password"`
}

type UserResponse struct {
	Message  string  `json:"message"`
	Status   int     `json:"status"`
	Data     *User   `json:"data"`
	DataList []*User `json:"dataList"`
}
